import { Post } from "./post";

export const monthNames = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

export const TECH_POSTS: Post[] = [
    {id:0, imgUrl:'../../../assets/img/blogs/website.jpg', category:'decision', when: 'October, 2018', title:'Why I decided to create a personal website', story:"Building a wesite meant a rigorous routine to handle my office, learn AngularJS and spend the rest of the time to build the website. Curiousity helped me initially to remained consistent in spending time on the exercise. But to take it through was a tough task."},
    {id:1, imgUrl:'../../../assets/img/blogs/graduation.jpg', category:'experience', when: 'October, 2018', title:'Graduating from VNIT, Nagpur', story:"Building a wesite meant a rigorous routine to handle my office, learn AngularJS and spend the rest of the time to build the website. Curiousity helped me initially to remained consistent in spending time on the exercise. But to take it through was a tough task."},
    {id:2, imgUrl:'../../../assets/img/blogs/messaging.jpg', category:'technology', when: 'October, 2018', title:'Apache Kafka as a Messaging Service', story:"Building a wesite meant a rigorous routine to handle my office, learn AngularJS and spend the rest of the time to build the website. Curiousity helped me initially to remained consistent in spending time on the exercise. But to take it through was a tough task."},
    {id:3, imgUrl:'../../../assets/img/blogs/business.jpg', category:'bussiness', when: 'October, 2018', title:'Puzzle Pieces in Bussiness Applications', story:"Building a wesite meant a rigorous routine to handle my office, learn AngularJS and spend the rest of the time to build the website. Curiousity helped me initially to remained consistent in spending time on the exercise. But to take it through was a tough task."},
    {id:4, imgUrl:'../../../assets/img/blogs/jagriti.jpg', category:'experience', when: 'October, 2018', title:'Jagriti Yatra', story:"Building a wesite meant a rigorous routine to handle my office, learn AngularJS and spend the rest of the time to build the website. Curiousity helped me initially to remained consistent in spending time on the exercise. But to take it through was a tough task."},
    {id:5, imgUrl:'../../../assets/img/blogs/mad.jpg', category:'experience', when: 'October, 2018', title:'Life at Make A Difference', story:"Building a wesite meant a rigorous routine to handle my office, learn AngularJS and spend the rest of the time to build the website. Curiousity helped me initially to remained consistent in spending time on the exercise. But to take it through was a tough task."},
];
export const OTHER_POSTS: Post[] = [
    /*{imgUrl:'none', category:'Family', when: 'August, 2017', title:'Love', story:'She asked her what she could do for her love. While all she could do was still fall in love.'},*/
    {id:0, imgUrl:'none', category:'Abstract', when: 'February, 2017', title:'She', story:"She was a different person to different people. An annoying younger sister to her brother. 'The-best-thing-that-happened' to her parents. 'A-good-friend' to her friends. Talented to her senior high school teacher. Quiet to a few. An idiot and even weird to other few. Unknown to a lot. But who was she, to herself?"},
    {id:1, imgUrl:'none', category:'Family', when: 'October, 2016', title:'Problems', story:"His brother could not find success in his career. His sister faked pregnancy out of pressure from the family. His own marriage was destroyed while his professional career saw a question mark. He felt cold. He had zero ways to sort things out. But, he just had to get a shawl, that was simple, like most other things."},
    /*{imgUrl:'none', category:'Nostalgia', when: 'September, 2016', title:'Routine', story:"Sneaking out of the first year hostel. Fire in the room. Stage plays at Compering. Morning walks in the campus. Proxies in the department. Cultural night, college gatherings and festivals. Extrapolated answers for the viva. Xeroxed notes for exams. Late night tarri-poha and samosas at Chandu. Long conversations and arguements on the hostel terrace. T.V. series. Teaching at the shelter homes. The Leadership circle. Conference calls. Core team meetings at Shivaji park. Hangouts at Goli and Hideout. Recruitment and City Circles. Dream Camps and the preparations. Post Dream Camp budget settlements. Cooking experiments. Night outs. Marriage scenes. Jagriti Yatra across the country. Lonavala Impromptu trip. Bhutan trip. Road trips. Placement scences in the final year. Placement treats. Tech-family treats. French classes. Well, the best you've ever had is just a memory and those dreams."},*/
    {id:2, imgUrl:'none', category:'Family', when: 'September, 2016', title:'Graduation', story:"36 hours to Convocation. His eyes watered as thoughts filled with all the memories gushed through. Pride, Excitement, Happyness, Numbness described the state of his mind at the moment. After four years of learning and hard work, his son was to be awarded his Engineering degree in the Convocation"},
    {id:3, imgUrl:'none', category:'Life', when: 'May, 2016', title:'Cancer', story:"Six year old with bilateral retinoblastoma. With the photon beam radiation, today the kid was graduating. Squamous cell lung cancer. 12 years in remission, the lady was able to walk her daughter down the aisle. Gastric adenocarcinoma. 15 years in remission, the woman could see her six grandchildren. And today, the oncologist himself was diagnosed with a terminal case of stomach cancer."},
    {id:4, imgUrl:'none', category:'Life', when: 'May, 2016', title:'Hit and Miss', story:"Pixel pitch: 4mu-m, Sensor size: 36X24mm, # pixels: 51MP, Video quality: 1080p 60fps. They got the best lenses in the market to capture the shots. Somewhere in the middle of perfectly capturing the moments, they missed the perfect moments"},
    {id:5, imgUrl:'none', category:'Love', when: 'April, 2016', title:'Relationship', story:'Their relationship was about to see a mutual end. She said the problem was she moved mountains for him while he hesitated to move a piece of land for her. The real problem was that the feeling was mutual.'},
    {id:6, imgUrl:'none', category:'Family', when: 'November, 2015', title:'Mother', story:"Last roti in the bowl. She said she was full. He ate it. The roti satisfied his hunger. As her stomach made funny noises, the sight of her son eating satisfied her's."},
    {id:7, imgUrl:'none', category:'History', when: 'October, 2015', title:'Perspectives', story:"After being a soldier in world war I, he found himself head of the government, fulfilling the dream of every poor and middle class person who ever sought to make it big. With his powerful intuition, oratory and bravery, he rallied the people and economy to create a powerful country. Some called him a patriot. Slaughtering innocent millions in concentration camps in inhumane conditions with the idea of creating of perfect race, few called him a vicious monster. Perspectives blinded the eyes of the truth"},
    {id:8, imgUrl:'none', category:'Life', when: 'September, 2015', title:'Care', story:"He had cancer. Chemotherapy had a painful chance of survival. She needed him, he cared about her. He took the chemo. A painful chance wasn't going to make it any better for him. But enduring excruciating pain for someone he cared about, was."},
    /*{imgUrl:'none', category:'', when: 'September, 2015', title:'', story:"She was eve-teased. Frustrated, she slapped him. All the suspicious eyes around started to stare him. Though she had slapped the wrong guy, he was glad she slapped."},*/
    {id:9, imgUrl:'none', category:'Thoughts', when: 'September, 2015', title:'Hate', story:"He kept a mental note of all the wrong he thought people did to him. He believed vengeance kept him alive, what he didn't realise was that it also burnt him alive., every hour of every day, every second."},
];

