import { Post } from './post';

export const TECH_POSTS: Post[] = [
    {id:'/blog/website', imgUrl:'blog-website', category:'decision', when: 'October, 2018', title:'Why I decided to create a personal website', story:"website.json"},
    {id:'/blog/graduation', imgUrl:'blog-graduation', category:'experience', when: 'October, 2018', title:'Graduating from VNIT, Nagpur', story:"graduation.json"},
    /*{id:'/blog/messaging', imgUrl:'blog-messaging', category:'technology', when: 'October, 2018', title:'Apache Kafka as a Messaging Service', story:"messaging.json"},*/
    /*{id:'/blog/business', imgUrl:'blog-business', category:'bussiness', when: 'October, 2018', title:'Puzzle Pieces in Bussiness Applications', story:"business.json"},*/
    /*{id:'/blog/jagriti', imgUrl:'blog-jagriti', category:'experience', when: 'October, 2018', title:'Jagriti Yatra', story:"jagriti.json"},*/
    {id:'/blog/mad', imgUrl:'blog-mad', category:'experience', when: 'October, 2018', title:'Life at Make A Difference', story:"mad.json"},
];
export const OTHER_POSTS: Post[] = [
    /*{imgUrl:'none', category:'Nostalgia', when: 'September, 2016', title:'Routine', story:"Sneaking out of the first year hostel. Fire in the room. Stage plays at Compering. Morning walks in the campus. Proxies in the department. Cultural night, college gatherings and festivals. Extrapolated answers for the viva. Xeroxed notes for exams. Late night tarri-poha and samosas at Chandu. Long conversations and arguements on the hostel terrace. T.V. series. Teaching at the shelter homes. The Leadership circle. Conference calls. Core team meetings at Shivaji park. Hangouts at Goli and Hideout. Recruitment and City Circles. Dream Camps and the preparations. Post Dream Camp budget settlements. Cooking experiments. Night outs. Marriage scenes. Jagriti Yatra across the country. Lonavala Impromptu trip. Bhutan trip. Road trips. Placement scences in the final year. Placement treats. Tech-family treats. French classes. Well, the best you've ever had is just a memory and those dreams."},*/
    {id:'/story/0', category:'Life', when: 'September, 2015', title:'Care', story:"He had cancer. Chemotherapy had a painful chance of survival. She needed him, he cared about her. He took the chemo. A painful chance wasn't going to make it any better for him. But enduring excruciating pain for someone he cared about, was."},
    {id:'/story/1', category:'Thoughts', when: 'September, 2015', title:'Hate', story:"He kept a mental note of all the wrong he thought people did to him. He believed vengeance kept him alive, what he didn't realise was that it also burnt him alive., every hour of every day, every second."},
    {id:'/story/2', category:'History', when: 'October, 2015', title:'Perspectives', story:"After being a soldier in world war I, he found himself head of the government, fulfilling the dream of every poor and middle class person who ever sought to make it big. With his powerful intuition, oratory and bravery, he rallied the people and economy to create a powerful country. Some called him a patriot. Slaughtering innocent millions in concentration camps in inhumane conditions with the idea of creating of perfect race, few called him a vicious monster. Perspectives blinded the eyes of the truth."},
    {id:'/story/3', category:'Family', when: 'November, 2015', title:'Mother', story:"Last roti in the bowl. She said she was full. He ate it. The roti satisfied his hunger. As her stomach made funny noises, the sight of her son eating satisfied her's."},
    {id:'/story/4', category:'Love', when: 'April, 2016', title:'Relationship', story:'Their relationship was about to see a mutual end. She said the problem was she moved mountains for him while he hesitated to move a piece of land for her. The real problem was that the feeling was mutual.'},
    {id:'/story/5', category:'Life', when: 'May, 2016', title:'Cancer', story:"Six year old with bilateral retinoblastoma. With the photon beam radiation, today the kid was graduating. Squamous cell lung cancer. 12 years in remission, the lady was able to walk her daughter down the aisle. Gastric adenocarcinoma. 15 years in remission, the woman could see her six grandchildren. And today, the oncologist himself was diagnosed with a terminal case of stomach cancer."},
    {id:'/story/6', category:'Life', when: 'May, 2016', title:'Hit and Miss', story:"Pixel pitch: 4mu-m, Sensor size: 36X24mm, # pixels: 51MP, Video quality: 1080p 60fps. They got the best lenses in the market to capture the shots. Somewhere in the middle of perfectly capturing the moments, they missed the perfect moments."},
    {id:'/story/7', category:'Family', when: 'September, 2016', title:'Graduation', story:"36 hours to Convocation. His eyes watered as thoughts filled with all the memories gushed through. Pride, Excitement, Happy-ness, Numbness described the state of his mind at the moment. After four years of learning and hard work, his son was to be awarded his Engineering degree in the Convocation."},
    {id:'/story/8', category:'Family', when: 'October, 2016', title:'Problems', story:"His brother could not find success in his career. His sister faked pregnancy out of pressure from the family. His own marriage was destroyed while his professional career saw a question mark. He felt cold. He had zero ways to sort things out. But, he just had to get a shawl, that was simple, like most other things."},
    {id:'/story/9', category:'Abstract', when: 'February, 2017', title:'She', story:"She was a different person to different people. An annoying younger sister to her brother. 'The-best-thing-that-happened' to her parents. 'A-good-friend' to her friends. Talented to her senior high school teacher. Quiet to a few. An idiot and even weird to other few. Unknown to a lot. But who was she, to herself?"},
    {id:'/story/10', category:'Love', when: 'August, 2017', title:'Article 377', story:'She asked her what she could do for her love. While all she could do was still fall in love.'},
    {id:'/story/11', category:'Love', when: 'February, 2020', title:'Arranged Love', story:'She was the best thing that happened to him. He was the perfect gentleman. Been together 8 years, they\'d never known how to live except with each other. Too bad, she worshipped the moon and he, the sun. Love was going to lose once again.'},
    {id:'/story/12', category:'History', when: 'March, 2020', title:'Anne Frank', story:'Year 1929, Young Jewish girl who lived in Nazi occupied Holland. 13 years old when her family went into hiding in a secret annexe, where she stayed for two years. Eventually betrayed, she died at the age of 16 in a concentration camp, from typhus. And she still believed that people are really good at heart. What\'s your excuse?'},
    {id:'/story/13', category:'Feminism', when: 'March, 2020', title:'The 2020 Girl', story:'She had aspirations and dreams. The society labelled her an ignorant and an arrogant, for having them. While, she was savage who knew exactly what she wanted, brave enough to fight for what she deserved. '},
    {id:'/story/14', category:'Patriarchy', when: 'April, 2020', title:'Killing it softly', story:'Months spent in quarantine. Complete lockdown., among all else, a few men had to learn to survive alone. Learn to clean the house, learn to cook, learn to wash the clothes., while the concept of patriarchy suffocated in the corner.'},
    {id:'/story/15', category:'Feminism', when: 'April, 2020', title:'Man of character', story:"She was being molested. Irritated, she slapped the guy behind him. All the suspicious eyes around started to stare him in ridicule. She had slapped the wrong guy, he was still glad she slapped."},
    {id:'/story/16', category:'Love', when: 'April, 2020', title:'Him and Her', story:"She was fierce. He was calm. She liked things clean. He, maybe, not so much. They both read a lot of books. He loved eating outside and she only ate healthy. They both loved to binge watch series and movies and go out on vacations. Just like that, together, they wrote their own marriage story.", dedication:"dedicating this bit to Rupali and Krishnakumar Mohta."},
    {id:'/story/17', category:'History', when: 'April, 2020', title:'Madiba', story:"27 years in a 7 cross 8 ft. prison with terrible living conditions, only to come out and forgive the ones who put him there in the first place. The country's first black head of state, his people fondly called him 'Madiba'."},
    {id:'/story/18', category:'Life', when: 'April, 2020', title:'Warrior', story:"On the best of days, she felt anxious. She felt the chaos running through her nerves, and some other times, she felt nothing. In some moments, she would imagine her whole world crumbling in front of her. But through this all, she kept constant that beautiful smile of hers. A girl like her was not to be found in songs or street, she was a warrior in the making."},
    {id:'/story/19', category:'Life', when: 'April, 2020', title:'Friends', story:"He was strong yet soft-hearted, even selfish, thankful, always choosing to see the good in others. He was a man, yet a child resided in him. His life seemed a mess, as nothing was working out. While his face wore a broad smile, his heart inflicted the wounds. But a few who stayed, those few moments full of life with them, made it worth his while."},
];
